federation_version: =2.2.1
subgraphs:
  authorization:
    routing_url: http://localhost:5001/graphql
    schema: 
      subgraph_url: http://localhost:5001/graphql
  accounts:
    routing_url: http://localhost:5002/graphql
    schema: 
      subgraph_url: http://localhost:5002/graphql